[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32H743VITx"
rustflags = [
  # flip-link not yet compatible alloc-cortex-m
  # https://github.com/knurling-rs/flip-link/issues/62
  # "-C",
  # "linker=flip-link",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C",
  "link-arg=--nmagic",
]

# Necessary to disable build target until bdk supports no_std
# cargo run -p vulcan --target thumbv7em-none-eabihf
# [build]
# target = "thumbv7em-none-eabihf"

[alias]
vulcan = "run -p vulcan --target thumbv7em-none-eabihf"
libvulcan = "run -p libvulcan"
rb = "run --bin"
rrb = "run --release --bin"
