[package]
name = "vulcan"
edition = "2018"
version = "0.1.0"

[dependencies]
alloc-cortex-m = "0.4.1"
cortex-m = "0.7.4"
cortex-m-rtic = "0.6.0-rc.4"
rtic-monotonic = "0.1.0-rc.2"
dwt-systick-monotonic = "0.1.0-rc.2"
systick-monotonic = "0.1.0-rc.2"
defmt = "0.2.3"
defmt-rtt = "0.2.0"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }
embedded-hal = "0.2.6"
stm32h7xx-hal = { git = "https://github.com/stm32-rs/stm32h7xx-hal", rev = "72adb08", features = [
  "stm32h743v",
  "sdmmc-fatfs",
  "rt",
  "rtc",
] }
embedded-graphics = "0.7.1"
heapless = { version = "0.7.7", features = ["ufmt-impl"] }
st7789 = "0.6.1"
display-interface = "0.4"
display-interface-spi = "0.4"
nb = "1.0.0"
embedded-layout = "0.2.0"
keypad2 = "0.1.1"
asm-delay = "0.9.0"
embedded-sdmmc = "0.3.0"
cortex-m-rt = "0.7.1"
embedded-qr = { git = "https://github.com/mcroad/embedded-qr" }
fatfs = { git = "https://github.com/rafalh/rust-fatfs", rev = "87fc1ed", default-features = false }

[features]
# set logging levels here
default = [
  "defmt-default",
  # "dependency-a/defmt-trace",
]

# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
